location ^~ /storage/ {
    alias /Users/rodrigue/Desktop/GokuSafiri/storage/app/public/;
    try_files $uri =404;
    access_log off;
    expires 30d;
    add_header Cache-Control "public, immutable";
}
